FROM golang:1.20.1-alpine

RUN mkdir /books-recommender

WORKDIR /books-recommender

# installing mockery for generating mocks
RUN go install github.com/vektra/mockery/v2@v2.20.0

COPY . .

# installing delve for debugging
RUN go install github.com/go-delve/delve/cmd/dlv@v1.20.1
