openapi: 3.0.3
info:
  title: books-recommender
  version: 1.0.0
  contact: {}
servers:
  - url: localhost
paths:
  /reading-interval:
    post:
      description: submit a new user intervale
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                book_id:
                  type: number
                  example: 5
                end_page:
                  type: number
                  example: 15
                start_page:
                  type: number
                  example: 1
                user_id:
                  type: number
                  example: 3
            examples:
              New Request:
                value:
                  book_id: 5
                  end_page: 15
                  start_page: 1
                  user_id: 3
      responses:
        '200':
          description: ''
  /recommend-books:
    get:
      description: get top read books
      responses:
        '200':
          description: ''
tags: []
