// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	entities "github.com/ahmedshakshak/books-recommender/entities"
	mock "github.com/stretchr/testify/mock"
)

// IUser is an autogenerated mock type for the IUser type
type IUser struct {
	mock.Mock
}

// SubmitReadingInterval provides a mock function with given fields: user, book
func (_m *IUser) SubmitReadingInterval(user *entities.User, book *entities.Book) error {
	ret := _m.Called(user, book)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.User, *entities.Book) error); ok {
		r0 = rf(user, book)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIUser interface {
	mock.TestingT
	Cleanup(func())
}

// NewIUser creates a new instance of IUser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIUser(t mockConstructorTestingTNewIUser) *IUser {
	mock := &IUser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
